BackendAdministrador:
        resource: "@CiudadTigreBackendBundle/Resources/config/routing/administrador.yml"
        prefix:   /administrador

BackendAnunciante:
    resource: "@CiudadTigreBackendBundle/Resources/config/routing/anunciante.yml"
    prefix:   /anunciante
    
BackendBanner:
    resource: "@CiudadTigreBackendBundle/Resources/config/routing/banner.yml"
    prefix:   /banner
    
BackendCategoria:
    resource: "@CiudadTigreBackendBundle/Resources/config/routing/categoria.yml"
    prefix:   /categoria

BackendSubcategoria:
        resource: "@CiudadTigreBackendBundle/Resources/config/routing/subcategoria.yml"
        prefix:   /subcategoria
        
backend_portada:
    path:     /
    defaults: { _controller: CiudadTigreBackendBundle:Default:index }

backend_login:
    pattern: /login
    defaults: { _controller: CiudadTigreBackendBundle:Default:login }
    
backend_login_check:
    pattern: /login_check

backend_logout:
    pattern: /logout
